//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from PineScript.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class PineScriptParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, COND=2, COND_ELSE=3, OR=4, AND=5, NOT=6, EQ=7, NEQ=8, GT=9, GE=10, 
		LT=11, LE=12, PLUS=13, MINUS=14, MUL=15, DIV=16, MOD=17, COMMA=18, ARROW=19, 
		LPAR=20, RPAR=21, LSQBR=22, RSQBR=23, DEFINE=24, IF_COND=25, IF_COND_ELSE=26, 
		BEGIN=27, END=28, ASSIGN=29, FOR_STMT=30, FOR_STMT_TO=31, FOR_STMT_BY=32, 
		BREAK=33, CONTINUE=34, INT_LITERAL=35, FLOAT_LITERAL=36, STR_LITERAL=37, 
		BOOL_LITERAL=38, COLOR_LITERAL=39, ID=40, ID_EX=41, INDENT=42, LINE_CONTINUATION=43, 
		EMPTY_LINE_V1=44, EMPTY_LINE=45, WHITESPACE=46;
	public const int
		RULE_script = 0, RULE_block = 1, RULE_statement = 2, RULE_variableDeclaration = 3, 
		RULE_variableAssignment = 4, RULE_variableValue = 5, RULE_functionDeclaration = 6, 
		RULE_functionParameters = 7, RULE_functionBody = 8, RULE_functionCall = 9, 
		RULE_functionArguments = 10, RULE_conditional = 11, RULE_conditionalElseBody = 12, 
		RULE_loop = 13, RULE_loopBody = 14, RULE_expression = 15, RULE_literal = 16, 
		RULE_seriesAccess = 17;
	public static readonly string[] ruleNames = {
		"script", "block", "statement", "variableDeclaration", "variableAssignment", 
		"variableValue", "functionDeclaration", "functionParameters", "functionBody", 
		"functionCall", "functionArguments", "conditional", "conditionalElseBody", 
		"loop", "loopBody", "expression", "literal", "seriesAccess"
	};

	private static readonly string[] _LiteralNames = {
		null, "'na'", "'?'", "':'", "'or'", "'and'", "'not'", "'=='", "'!='", 
		"'>'", "'>='", "'<'", "'<='", "'+'", "'-'", "'*'", "'/'", "'%'", "','", 
		"'=>'", "'('", "')'", "'['", "']'", "'='", "'if'", "'else'", "'|BEGIN|'", 
		"'|END|'", "':='", "'for'", "'to'", "'by'", "'break'", "'continue'", null, 
		null, null, null, null, null, null, "'|INDENT|'", "'|C|'", "'|EMPTY_V1|'", 
		"'|EMPTY|'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, "COND", "COND_ELSE", "OR", "AND", "NOT", "EQ", "NEQ", "GT", 
		"GE", "LT", "LE", "PLUS", "MINUS", "MUL", "DIV", "MOD", "COMMA", "ARROW", 
		"LPAR", "RPAR", "LSQBR", "RSQBR", "DEFINE", "IF_COND", "IF_COND_ELSE", 
		"BEGIN", "END", "ASSIGN", "FOR_STMT", "FOR_STMT_TO", "FOR_STMT_BY", "BREAK", 
		"CONTINUE", "INT_LITERAL", "FLOAT_LITERAL", "STR_LITERAL", "BOOL_LITERAL", 
		"COLOR_LITERAL", "ID", "ID_EX", "INDENT", "LINE_CONTINUATION", "EMPTY_LINE_V1", 
		"EMPTY_LINE", "WHITESPACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "PineScript.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static PineScriptParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public PineScriptParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public PineScriptParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ScriptContext : ParserRuleContext {
		public StatementContext statements;
		public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ScriptContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_script; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterScript(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitScript(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitScript(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ScriptContext script() {
		ScriptContext _localctx = new ScriptContext(Context, State);
		EnterRule(_localctx, 0, RULE_script);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 37;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 36; _localctx.statements = statement();
				}
				}
				State = 39;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << IF_COND) | (1L << FOR_STMT) | (1L << ID))) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockContext : ParserRuleContext {
		public ITerminalNode BEGIN() { return GetToken(PineScriptParser.BEGIN, 0); }
		public ITerminalNode END() { return GetToken(PineScriptParser.END, 0); }
		public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterBlock(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitBlock(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(Context, State);
		EnterRule(_localctx, 2, RULE_block);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 41; Match(BEGIN);
			State = 43;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 42; statement();
				}
				}
				State = 45;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << IF_COND) | (1L << FOR_STMT) | (1L << ID))) != 0) );
			State = 47; Match(END);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		public VariableDeclarationContext variableDeclaration() {
			return GetRuleContext<VariableDeclarationContext>(0);
		}
		public VariableAssignmentContext variableAssignment() {
			return GetRuleContext<VariableAssignmentContext>(0);
		}
		public FunctionDeclarationContext functionDeclaration() {
			return GetRuleContext<FunctionDeclarationContext>(0);
		}
		public FunctionCallContext functionCall() {
			return GetRuleContext<FunctionCallContext>(0);
		}
		public ConditionalContext conditional() {
			return GetRuleContext<ConditionalContext>(0);
		}
		public LoopContext loop() {
			return GetRuleContext<LoopContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 4, RULE_statement);
		try {
			State = 55;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 49; variableDeclaration();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 50; variableAssignment();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 51; functionDeclaration();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 52; functionCall();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 53; conditional();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 54; loop();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableDeclarationContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(PineScriptParser.ID, 0); }
		public ITerminalNode DEFINE() { return GetToken(PineScriptParser.DEFINE, 0); }
		public VariableValueContext variableValue() {
			return GetRuleContext<VariableValueContext>(0);
		}
		public VariableDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variableDeclaration; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterVariableDeclaration(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitVariableDeclaration(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableDeclarationContext variableDeclaration() {
		VariableDeclarationContext _localctx = new VariableDeclarationContext(Context, State);
		EnterRule(_localctx, 6, RULE_variableDeclaration);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 57; Match(ID);
			State = 58; Match(DEFINE);
			State = 59; variableValue();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableAssignmentContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(PineScriptParser.ID, 0); }
		public ITerminalNode ASSIGN() { return GetToken(PineScriptParser.ASSIGN, 0); }
		public VariableValueContext variableValue() {
			return GetRuleContext<VariableValueContext>(0);
		}
		public VariableAssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variableAssignment; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterVariableAssignment(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitVariableAssignment(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableAssignment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableAssignmentContext variableAssignment() {
		VariableAssignmentContext _localctx = new VariableAssignmentContext(Context, State);
		EnterRule(_localctx, 8, RULE_variableAssignment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 61; Match(ID);
			State = 62; Match(ASSIGN);
			State = 63; variableValue();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableValueContext : ParserRuleContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ConditionalContext conditional() {
			return GetRuleContext<ConditionalContext>(0);
		}
		public LoopContext loop() {
			return GetRuleContext<LoopContext>(0);
		}
		public VariableValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variableValue; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterVariableValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitVariableValue(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableValueContext variableValue() {
		VariableValueContext _localctx = new VariableValueContext(Context, State);
		EnterRule(_localctx, 10, RULE_variableValue);
		try {
			State = 68;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__0:
			case NOT:
			case MINUS:
			case LPAR:
			case INT_LITERAL:
			case FLOAT_LITERAL:
			case STR_LITERAL:
			case BOOL_LITERAL:
			case COLOR_LITERAL:
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 65; expression(0);
				}
				break;
			case IF_COND:
				EnterOuterAlt(_localctx, 2);
				{
				State = 66; conditional();
				}
				break;
			case FOR_STMT:
				EnterOuterAlt(_localctx, 3);
				{
				State = 67; loop();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionDeclarationContext : ParserRuleContext {
		public IToken name;
		public ITerminalNode LPAR() { return GetToken(PineScriptParser.LPAR, 0); }
		public FunctionParametersContext functionParameters() {
			return GetRuleContext<FunctionParametersContext>(0);
		}
		public ITerminalNode RPAR() { return GetToken(PineScriptParser.RPAR, 0); }
		public ITerminalNode ARROW() { return GetToken(PineScriptParser.ARROW, 0); }
		public FunctionBodyContext functionBody() {
			return GetRuleContext<FunctionBodyContext>(0);
		}
		public ITerminalNode ID() { return GetToken(PineScriptParser.ID, 0); }
		public FunctionDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionDeclaration; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterFunctionDeclaration(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitFunctionDeclaration(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionDeclarationContext functionDeclaration() {
		FunctionDeclarationContext _localctx = new FunctionDeclarationContext(Context, State);
		EnterRule(_localctx, 12, RULE_functionDeclaration);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 70; _localctx.name = Match(ID);
			State = 71; Match(LPAR);
			State = 72; functionParameters();
			State = 73; Match(RPAR);
			State = 74; Match(ARROW);
			State = 75; functionBody();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionParametersContext : ParserRuleContext {
		public ITerminalNode[] ID() { return GetTokens(PineScriptParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(PineScriptParser.ID, i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(PineScriptParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(PineScriptParser.COMMA, i);
		}
		public FunctionParametersContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionParameters; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterFunctionParameters(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitFunctionParameters(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionParameters(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionParametersContext functionParameters() {
		FunctionParametersContext _localctx = new FunctionParametersContext(Context, State);
		EnterRule(_localctx, 14, RULE_functionParameters);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 85;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ID) {
				{
				State = 77; Match(ID);
				State = 82;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 78; Match(COMMA);
					State = 79; Match(ID);
					}
					}
					State = 84;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionBodyContext : ParserRuleContext {
		public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public FunctionBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionBody; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterFunctionBody(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitFunctionBody(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionBody(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionBodyContext functionBody() {
		FunctionBodyContext _localctx = new FunctionBodyContext(Context, State);
		EnterRule(_localctx, 16, RULE_functionBody);
		try {
			State = 89;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case BEGIN:
				EnterOuterAlt(_localctx, 1);
				{
				State = 87; block();
				}
				break;
			case T__0:
			case NOT:
			case MINUS:
			case LPAR:
			case INT_LITERAL:
			case FLOAT_LITERAL:
			case STR_LITERAL:
			case BOOL_LITERAL:
			case COLOR_LITERAL:
			case ID:
				EnterOuterAlt(_localctx, 2);
				{
				State = 88; expression(0);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionCallContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(PineScriptParser.ID, 0); }
		public ITerminalNode LPAR() { return GetToken(PineScriptParser.LPAR, 0); }
		public FunctionArgumentsContext functionArguments() {
			return GetRuleContext<FunctionArgumentsContext>(0);
		}
		public ITerminalNode RPAR() { return GetToken(PineScriptParser.RPAR, 0); }
		public FunctionCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionCall; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterFunctionCall(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitFunctionCall(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionCallContext functionCall() {
		FunctionCallContext _localctx = new FunctionCallContext(Context, State);
		EnterRule(_localctx, 18, RULE_functionCall);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 91; Match(ID);
			State = 92; Match(LPAR);
			State = 93; functionArguments();
			State = 94; Match(RPAR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionArgumentsContext : ParserRuleContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(PineScriptParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(PineScriptParser.COMMA, i);
		}
		public VariableDeclarationContext[] variableDeclaration() {
			return GetRuleContexts<VariableDeclarationContext>();
		}
		public VariableDeclarationContext variableDeclaration(int i) {
			return GetRuleContext<VariableDeclarationContext>(i);
		}
		public FunctionArgumentsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionArguments; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterFunctionArguments(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitFunctionArguments(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionArguments(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionArgumentsContext functionArguments() {
		FunctionArgumentsContext _localctx = new FunctionArgumentsContext(Context, State);
		EnterRule(_localctx, 20, RULE_functionArguments);
		int _la;
		try {
			int _alt;
			State = 123;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 111;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << NOT) | (1L << MINUS) | (1L << LPAR) | (1L << INT_LITERAL) | (1L << FLOAT_LITERAL) | (1L << STR_LITERAL) | (1L << BOOL_LITERAL) | (1L << COLOR_LITERAL) | (1L << ID))) != 0)) {
					{
					State = 96; expression(0);
					State = 101;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,7,Context);
					while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
						if ( _alt==1 ) {
							{
							{
							State = 97; Match(COMMA);
							State = 98; expression(0);
							}
							} 
						}
						State = 103;
						ErrorHandler.Sync(this);
						_alt = Interpreter.AdaptivePredict(TokenStream,7,Context);
					}
					State = 108;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==COMMA) {
						{
						{
						State = 104; Match(COMMA);
						State = 105; variableDeclaration();
						}
						}
						State = 110;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 121;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==ID) {
					{
					State = 113; variableDeclaration();
					State = 118;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==COMMA) {
						{
						{
						State = 114; Match(COMMA);
						State = 115; variableDeclaration();
						}
						}
						State = 120;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConditionalContext : ParserRuleContext {
		public ExpressionContext condition;
		public BlockContext then;
		public ConditionalElseBodyContext @else;
		public ITerminalNode IF_COND() { return GetToken(PineScriptParser.IF_COND, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public ITerminalNode IF_COND_ELSE() { return GetToken(PineScriptParser.IF_COND_ELSE, 0); }
		public ConditionalElseBodyContext conditionalElseBody() {
			return GetRuleContext<ConditionalElseBodyContext>(0);
		}
		public ConditionalContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_conditional; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterConditional(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitConditional(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConditional(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConditionalContext conditional() {
		ConditionalContext _localctx = new ConditionalContext(Context, State);
		EnterRule(_localctx, 22, RULE_conditional);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 125; Match(IF_COND);
			State = 126; _localctx.condition = expression(0);
			State = 127; _localctx.then = block();
			State = 130;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==IF_COND_ELSE) {
				{
				State = 128; Match(IF_COND_ELSE);
				State = 129; _localctx.@else = conditionalElseBody();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConditionalElseBodyContext : ParserRuleContext {
		public ConditionalContext conditional() {
			return GetRuleContext<ConditionalContext>(0);
		}
		public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public ConditionalElseBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_conditionalElseBody; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterConditionalElseBody(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitConditionalElseBody(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConditionalElseBody(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConditionalElseBodyContext conditionalElseBody() {
		ConditionalElseBodyContext _localctx = new ConditionalElseBodyContext(Context, State);
		EnterRule(_localctx, 24, RULE_conditionalElseBody);
		try {
			State = 134;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case IF_COND:
				EnterOuterAlt(_localctx, 1);
				{
				State = 132; conditional();
				}
				break;
			case BEGIN:
				EnterOuterAlt(_localctx, 2);
				{
				State = 133; block();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LoopContext : ParserRuleContext {
		public IToken step;
		public ITerminalNode FOR_STMT() { return GetToken(PineScriptParser.FOR_STMT, 0); }
		public VariableDeclarationContext variableDeclaration() {
			return GetRuleContext<VariableDeclarationContext>(0);
		}
		public ITerminalNode FOR_STMT_TO() { return GetToken(PineScriptParser.FOR_STMT_TO, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ITerminalNode BEGIN() { return GetToken(PineScriptParser.BEGIN, 0); }
		public LoopBodyContext loopBody() {
			return GetRuleContext<LoopBodyContext>(0);
		}
		public ITerminalNode END() { return GetToken(PineScriptParser.END, 0); }
		public ITerminalNode FOR_STMT_BY() { return GetToken(PineScriptParser.FOR_STMT_BY, 0); }
		public ITerminalNode INT_LITERAL() { return GetToken(PineScriptParser.INT_LITERAL, 0); }
		public LoopContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_loop; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterLoop(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitLoop(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLoop(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LoopContext loop() {
		LoopContext _localctx = new LoopContext(Context, State);
		EnterRule(_localctx, 26, RULE_loop);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 136; Match(FOR_STMT);
			State = 137; variableDeclaration();
			State = 138; Match(FOR_STMT_TO);
			State = 139; expression(0);
			State = 142;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==FOR_STMT_BY) {
				{
				State = 140; Match(FOR_STMT_BY);
				State = 141; _localctx.step = Match(INT_LITERAL);
				}
			}

			State = 144; Match(BEGIN);
			State = 145; loopBody();
			State = 146; Match(END);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LoopBodyContext : ParserRuleContext {
		public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ITerminalNode[] BREAK() { return GetTokens(PineScriptParser.BREAK); }
		public ITerminalNode BREAK(int i) {
			return GetToken(PineScriptParser.BREAK, i);
		}
		public ITerminalNode[] CONTINUE() { return GetTokens(PineScriptParser.CONTINUE); }
		public ITerminalNode CONTINUE(int i) {
			return GetToken(PineScriptParser.CONTINUE, i);
		}
		public LoopBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_loopBody; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterLoopBody(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitLoopBody(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLoopBody(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LoopBodyContext loopBody() {
		LoopBodyContext _localctx = new LoopBodyContext(Context, State);
		EnterRule(_localctx, 28, RULE_loopBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 151;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				State = 151;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case IF_COND:
				case FOR_STMT:
				case ID:
					{
					State = 148; statement();
					}
					break;
				case BREAK:
					{
					State = 149; Match(BREAK);
					}
					break;
				case CONTINUE:
					{
					State = 150; Match(CONTINUE);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 153;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << IF_COND) | (1L << FOR_STMT) | (1L << BREAK) | (1L << CONTINUE) | (1L << ID))) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
	 
		public ExpressionContext() { }
		public virtual void CopyFrom(ExpressionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ParenthesizedExpressionContext : ExpressionContext {
		public ITerminalNode LPAR() { return GetToken(PineScriptParser.LPAR, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ITerminalNode RPAR() { return GetToken(PineScriptParser.RPAR, 0); }
		public ParenthesizedExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterParenthesizedExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitParenthesizedExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParenthesizedExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class TernaryExpressionContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode COND() { return GetToken(PineScriptParser.COND, 0); }
		public ITerminalNode COND_ELSE() { return GetToken(PineScriptParser.COND_ELSE, 0); }
		public TernaryExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterTernaryExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitTernaryExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTernaryExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class UnaryMinusExpressionContext : ExpressionContext {
		public ITerminalNode MINUS() { return GetToken(PineScriptParser.MINUS, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public UnaryMinusExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterUnaryMinusExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitUnaryMinusExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryMinusExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BinaryOperationExpressionContext : ExpressionContext {
		public IToken op;
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode MUL() { return GetToken(PineScriptParser.MUL, 0); }
		public ITerminalNode DIV() { return GetToken(PineScriptParser.DIV, 0); }
		public ITerminalNode MOD() { return GetToken(PineScriptParser.MOD, 0); }
		public ITerminalNode PLUS() { return GetToken(PineScriptParser.PLUS, 0); }
		public ITerminalNode MINUS() { return GetToken(PineScriptParser.MINUS, 0); }
		public ITerminalNode GE() { return GetToken(PineScriptParser.GE, 0); }
		public ITerminalNode LE() { return GetToken(PineScriptParser.LE, 0); }
		public ITerminalNode GT() { return GetToken(PineScriptParser.GT, 0); }
		public ITerminalNode LT() { return GetToken(PineScriptParser.LT, 0); }
		public ITerminalNode EQ() { return GetToken(PineScriptParser.EQ, 0); }
		public ITerminalNode NEQ() { return GetToken(PineScriptParser.NEQ, 0); }
		public ITerminalNode AND() { return GetToken(PineScriptParser.AND, 0); }
		public ITerminalNode OR() { return GetToken(PineScriptParser.OR, 0); }
		public BinaryOperationExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterBinaryOperationExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitBinaryOperationExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinaryOperationExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class LiteralExpressionContext : ExpressionContext {
		public LiteralContext literal() {
			return GetRuleContext<LiteralContext>(0);
		}
		public LiteralExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterLiteralExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitLiteralExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLiteralExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NotExpressionContext : ExpressionContext {
		public ITerminalNode NOT() { return GetToken(PineScriptParser.NOT, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public NotExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterNotExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitNotExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNotExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionCallExpressionContext : ExpressionContext {
		public FunctionCallContext functionCall() {
			return GetRuleContext<FunctionCallContext>(0);
		}
		public FunctionCallExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterFunctionCallExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitFunctionCallExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionCallExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IdentifierExpressionContext : ExpressionContext {
		public SeriesAccessContext seriesAccess() {
			return GetRuleContext<SeriesAccessContext>(0);
		}
		public ITerminalNode ID() { return GetToken(PineScriptParser.ID, 0); }
		public IdentifierExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterIdentifierExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitIdentifierExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdentifierExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		return expression(0);
	}

	private ExpressionContext expression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExpressionContext _localctx = new ExpressionContext(Context, _parentState);
		ExpressionContext _prevctx = _localctx;
		int _startState = 30;
		EnterRecursionRule(_localctx, 30, RULE_expression, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 170;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,19,Context) ) {
			case 1:
				{
				_localctx = new UnaryMinusExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 156; Match(MINUS);
				State = 157; expression(13);
				}
				break;
			case 2:
				{
				_localctx = new NotExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 158; Match(NOT);
				State = 159; expression(12);
				}
				break;
			case 3:
				{
				_localctx = new LiteralExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 160; literal();
				}
				break;
			case 4:
				{
				_localctx = new FunctionCallExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 161; functionCall();
				}
				break;
			case 5:
				{
				_localctx = new IdentifierExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 164;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,18,Context) ) {
				case 1:
					{
					State = 162; seriesAccess();
					}
					break;
				case 2:
					{
					State = 163; Match(ID);
					}
					break;
				}
				}
				break;
			case 6:
				{
				_localctx = new ParenthesizedExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 166; Match(LPAR);
				State = 167; expression(0);
				State = 168; Match(RPAR);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 198;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,21,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 196;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,20,Context) ) {
					case 1:
						{
						_localctx = new BinaryOperationExpressionContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 172;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 173;
						((BinaryOperationExpressionContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << MUL) | (1L << DIV) | (1L << MOD))) != 0)) ) {
							((BinaryOperationExpressionContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 174; expression(12);
						}
						break;
					case 2:
						{
						_localctx = new BinaryOperationExpressionContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 175;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 176;
						((BinaryOperationExpressionContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==PLUS || _la==MINUS) ) {
							((BinaryOperationExpressionContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 177; expression(11);
						}
						break;
					case 3:
						{
						_localctx = new BinaryOperationExpressionContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 178;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 179;
						((BinaryOperationExpressionContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << GT) | (1L << GE) | (1L << LT) | (1L << LE))) != 0)) ) {
							((BinaryOperationExpressionContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 180; expression(10);
						}
						break;
					case 4:
						{
						_localctx = new BinaryOperationExpressionContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 181;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 182;
						((BinaryOperationExpressionContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==EQ || _la==NEQ) ) {
							((BinaryOperationExpressionContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 183; expression(9);
						}
						break;
					case 5:
						{
						_localctx = new BinaryOperationExpressionContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 184;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 185; ((BinaryOperationExpressionContext)_localctx).op = Match(AND);
						State = 186; expression(8);
						}
						break;
					case 6:
						{
						_localctx = new BinaryOperationExpressionContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 187;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 188; ((BinaryOperationExpressionContext)_localctx).op = Match(OR);
						State = 189; expression(7);
						}
						break;
					case 7:
						{
						_localctx = new TernaryExpressionContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 190;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 191; Match(COND);
						State = 192; expression(0);
						State = 193; Match(COND_ELSE);
						State = 194; expression(6);
						}
						break;
					}
					} 
				}
				State = 200;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,21,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class LiteralContext : ParserRuleContext {
		public LiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_literal; } }
	 
		public LiteralContext() { }
		public virtual void CopyFrom(LiteralContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ColorLiteralContext : LiteralContext {
		public ITerminalNode COLOR_LITERAL() { return GetToken(PineScriptParser.COLOR_LITERAL, 0); }
		public ColorLiteralContext(LiteralContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterColorLiteral(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitColorLiteral(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitColorLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NALiteralContext : LiteralContext {
		public NALiteralContext(LiteralContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterNALiteral(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitNALiteral(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNALiteral(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BoolLiteralContext : LiteralContext {
		public ITerminalNode BOOL_LITERAL() { return GetToken(PineScriptParser.BOOL_LITERAL, 0); }
		public BoolLiteralContext(LiteralContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterBoolLiteral(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitBoolLiteral(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBoolLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class StringLiteralContext : LiteralContext {
		public ITerminalNode STR_LITERAL() { return GetToken(PineScriptParser.STR_LITERAL, 0); }
		public StringLiteralContext(LiteralContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterStringLiteral(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitStringLiteral(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStringLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FloatLiteralContext : LiteralContext {
		public ITerminalNode FLOAT_LITERAL() { return GetToken(PineScriptParser.FLOAT_LITERAL, 0); }
		public FloatLiteralContext(LiteralContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterFloatLiteral(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitFloatLiteral(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFloatLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IntLiteralContext : LiteralContext {
		public ITerminalNode INT_LITERAL() { return GetToken(PineScriptParser.INT_LITERAL, 0); }
		public IntLiteralContext(LiteralContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterIntLiteral(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitIntLiteral(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIntLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LiteralContext literal() {
		LiteralContext _localctx = new LiteralContext(Context, State);
		EnterRule(_localctx, 32, RULE_literal);
		try {
			State = 207;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INT_LITERAL:
				_localctx = new IntLiteralContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 201; Match(INT_LITERAL);
				}
				break;
			case FLOAT_LITERAL:
				_localctx = new FloatLiteralContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 202; Match(FLOAT_LITERAL);
				}
				break;
			case BOOL_LITERAL:
				_localctx = new BoolLiteralContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 203; Match(BOOL_LITERAL);
				}
				break;
			case STR_LITERAL:
				_localctx = new StringLiteralContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 204; Match(STR_LITERAL);
				}
				break;
			case COLOR_LITERAL:
				_localctx = new ColorLiteralContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 205; Match(COLOR_LITERAL);
				}
				break;
			case T__0:
				_localctx = new NALiteralContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 206; Match(T__0);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SeriesAccessContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(PineScriptParser.ID, 0); }
		public ITerminalNode LSQBR() { return GetToken(PineScriptParser.LSQBR, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ITerminalNode RSQBR() { return GetToken(PineScriptParser.RSQBR, 0); }
		public SeriesAccessContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_seriesAccess; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterSeriesAccess(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitSeriesAccess(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSeriesAccess(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SeriesAccessContext seriesAccess() {
		SeriesAccessContext _localctx = new SeriesAccessContext(Context, State);
		EnterRule(_localctx, 34, RULE_seriesAccess);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 209; Match(ID);
			State = 210; Match(LSQBR);
			State = 211; expression(0);
			State = 212; Match(RSQBR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 15: return expression_sempred((ExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expression_sempred(ExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 11);
		case 1: return Precpred(Context, 10);
		case 2: return Precpred(Context, 9);
		case 3: return Precpred(Context, 8);
		case 4: return Precpred(Context, 7);
		case 5: return Precpred(Context, 6);
		case 6: return Precpred(Context, 5);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x30', '\xD9', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x3', '\x2', '\x6', '\x2', '(', '\n', '\x2', '\r', '\x2', '\xE', 
		'\x2', ')', '\x3', '\x3', '\x3', '\x3', '\x6', '\x3', '.', '\n', '\x3', 
		'\r', '\x3', '\xE', '\x3', '/', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x5', '\x4', ':', '\n', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x5', '\a', 'G', '\n', '\a', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\a', '\t', 'S', '\n', 
		'\t', '\f', '\t', '\xE', '\t', 'V', '\v', '\t', '\x5', '\t', 'X', '\n', 
		'\t', '\x3', '\n', '\x3', '\n', '\x5', '\n', '\\', '\n', '\n', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\a', '\f', '\x66', '\n', '\f', '\f', '\f', 
		'\xE', '\f', 'i', '\v', '\f', '\x3', '\f', '\x3', '\f', '\a', '\f', 'm', 
		'\n', '\f', '\f', '\f', '\xE', '\f', 'p', '\v', '\f', '\x5', '\f', 'r', 
		'\n', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\a', '\f', 'w', '\n', 
		'\f', '\f', '\f', '\xE', '\f', 'z', '\v', '\f', '\x5', '\f', '|', '\n', 
		'\f', '\x5', '\f', '~', '\n', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x5', '\r', '\x85', '\n', '\r', '\x3', '\xE', 
		'\x3', '\xE', '\x5', '\xE', '\x89', '\n', '\xE', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x5', 
		'\xF', '\x91', '\n', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x6', '\x10', 
		'\x9A', '\n', '\x10', '\r', '\x10', '\xE', '\x10', '\x9B', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x5', '\x11', '\xA7', '\n', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x5', 
		'\x11', '\xAD', '\n', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\a', '\x11', '\xC7', '\n', '\x11', '\f', '\x11', '\xE', 
		'\x11', '\xCA', '\v', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x5', '\x12', '\xD2', '\n', 
		'\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\x2', '\x3', ' ', '\x14', '\x2', '\x4', '\x6', 
		'\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', '\x18', '\x1A', 
		'\x1C', '\x1E', ' ', '\"', '$', '\x2', '\x6', '\x3', '\x2', '\x11', '\x13', 
		'\x3', '\x2', '\xF', '\x10', '\x3', '\x2', '\v', '\xE', '\x3', '\x2', 
		'\t', '\n', '\x2', '\xF0', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x4', 
		'+', '\x3', '\x2', '\x2', '\x2', '\x6', '\x39', '\x3', '\x2', '\x2', '\x2', 
		'\b', ';', '\x3', '\x2', '\x2', '\x2', '\n', '?', '\x3', '\x2', '\x2', 
		'\x2', '\f', '\x46', '\x3', '\x2', '\x2', '\x2', '\xE', 'H', '\x3', '\x2', 
		'\x2', '\x2', '\x10', 'W', '\x3', '\x2', '\x2', '\x2', '\x12', '[', '\x3', 
		'\x2', '\x2', '\x2', '\x14', ']', '\x3', '\x2', '\x2', '\x2', '\x16', 
		'}', '\x3', '\x2', '\x2', '\x2', '\x18', '\x7F', '\x3', '\x2', '\x2', 
		'\x2', '\x1A', '\x88', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x8A', '\x3', 
		'\x2', '\x2', '\x2', '\x1E', '\x99', '\x3', '\x2', '\x2', '\x2', ' ', 
		'\xAC', '\x3', '\x2', '\x2', '\x2', '\"', '\xD1', '\x3', '\x2', '\x2', 
		'\x2', '$', '\xD3', '\x3', '\x2', '\x2', '\x2', '&', '(', '\x5', '\x6', 
		'\x4', '\x2', '\'', '&', '\x3', '\x2', '\x2', '\x2', '(', ')', '\x3', 
		'\x2', '\x2', '\x2', ')', '\'', '\x3', '\x2', '\x2', '\x2', ')', '*', 
		'\x3', '\x2', '\x2', '\x2', '*', '\x3', '\x3', '\x2', '\x2', '\x2', '+', 
		'-', '\a', '\x1D', '\x2', '\x2', ',', '.', '\x5', '\x6', '\x4', '\x2', 
		'-', ',', '\x3', '\x2', '\x2', '\x2', '.', '/', '\x3', '\x2', '\x2', '\x2', 
		'/', '-', '\x3', '\x2', '\x2', '\x2', '/', '\x30', '\x3', '\x2', '\x2', 
		'\x2', '\x30', '\x31', '\x3', '\x2', '\x2', '\x2', '\x31', '\x32', '\a', 
		'\x1E', '\x2', '\x2', '\x32', '\x5', '\x3', '\x2', '\x2', '\x2', '\x33', 
		':', '\x5', '\b', '\x5', '\x2', '\x34', ':', '\x5', '\n', '\x6', '\x2', 
		'\x35', ':', '\x5', '\xE', '\b', '\x2', '\x36', ':', '\x5', '\x14', '\v', 
		'\x2', '\x37', ':', '\x5', '\x18', '\r', '\x2', '\x38', ':', '\x5', '\x1C', 
		'\xF', '\x2', '\x39', '\x33', '\x3', '\x2', '\x2', '\x2', '\x39', '\x34', 
		'\x3', '\x2', '\x2', '\x2', '\x39', '\x35', '\x3', '\x2', '\x2', '\x2', 
		'\x39', '\x36', '\x3', '\x2', '\x2', '\x2', '\x39', '\x37', '\x3', '\x2', 
		'\x2', '\x2', '\x39', '\x38', '\x3', '\x2', '\x2', '\x2', ':', '\a', '\x3', 
		'\x2', '\x2', '\x2', ';', '<', '\a', '*', '\x2', '\x2', '<', '=', '\a', 
		'\x1A', '\x2', '\x2', '=', '>', '\x5', '\f', '\a', '\x2', '>', '\t', '\x3', 
		'\x2', '\x2', '\x2', '?', '@', '\a', '*', '\x2', '\x2', '@', '\x41', '\a', 
		'\x1F', '\x2', '\x2', '\x41', '\x42', '\x5', '\f', '\a', '\x2', '\x42', 
		'\v', '\x3', '\x2', '\x2', '\x2', '\x43', 'G', '\x5', ' ', '\x11', '\x2', 
		'\x44', 'G', '\x5', '\x18', '\r', '\x2', '\x45', 'G', '\x5', '\x1C', '\xF', 
		'\x2', '\x46', '\x43', '\x3', '\x2', '\x2', '\x2', '\x46', '\x44', '\x3', 
		'\x2', '\x2', '\x2', '\x46', '\x45', '\x3', '\x2', '\x2', '\x2', 'G', 
		'\r', '\x3', '\x2', '\x2', '\x2', 'H', 'I', '\a', '*', '\x2', '\x2', 'I', 
		'J', '\a', '\x16', '\x2', '\x2', 'J', 'K', '\x5', '\x10', '\t', '\x2', 
		'K', 'L', '\a', '\x17', '\x2', '\x2', 'L', 'M', '\a', '\x15', '\x2', '\x2', 
		'M', 'N', '\x5', '\x12', '\n', '\x2', 'N', '\xF', '\x3', '\x2', '\x2', 
		'\x2', 'O', 'T', '\a', '*', '\x2', '\x2', 'P', 'Q', '\a', '\x14', '\x2', 
		'\x2', 'Q', 'S', '\a', '*', '\x2', '\x2', 'R', 'P', '\x3', '\x2', '\x2', 
		'\x2', 'S', 'V', '\x3', '\x2', '\x2', '\x2', 'T', 'R', '\x3', '\x2', '\x2', 
		'\x2', 'T', 'U', '\x3', '\x2', '\x2', '\x2', 'U', 'X', '\x3', '\x2', '\x2', 
		'\x2', 'V', 'T', '\x3', '\x2', '\x2', '\x2', 'W', 'O', '\x3', '\x2', '\x2', 
		'\x2', 'W', 'X', '\x3', '\x2', '\x2', '\x2', 'X', '\x11', '\x3', '\x2', 
		'\x2', '\x2', 'Y', '\\', '\x5', '\x4', '\x3', '\x2', 'Z', '\\', '\x5', 
		' ', '\x11', '\x2', '[', 'Y', '\x3', '\x2', '\x2', '\x2', '[', 'Z', '\x3', 
		'\x2', '\x2', '\x2', '\\', '\x13', '\x3', '\x2', '\x2', '\x2', ']', '^', 
		'\a', '*', '\x2', '\x2', '^', '_', '\a', '\x16', '\x2', '\x2', '_', '`', 
		'\x5', '\x16', '\f', '\x2', '`', '\x61', '\a', '\x17', '\x2', '\x2', '\x61', 
		'\x15', '\x3', '\x2', '\x2', '\x2', '\x62', 'g', '\x5', ' ', '\x11', '\x2', 
		'\x63', '\x64', '\a', '\x14', '\x2', '\x2', '\x64', '\x66', '\x5', ' ', 
		'\x11', '\x2', '\x65', '\x63', '\x3', '\x2', '\x2', '\x2', '\x66', 'i', 
		'\x3', '\x2', '\x2', '\x2', 'g', '\x65', '\x3', '\x2', '\x2', '\x2', 'g', 
		'h', '\x3', '\x2', '\x2', '\x2', 'h', 'n', '\x3', '\x2', '\x2', '\x2', 
		'i', 'g', '\x3', '\x2', '\x2', '\x2', 'j', 'k', '\a', '\x14', '\x2', '\x2', 
		'k', 'm', '\x5', '\b', '\x5', '\x2', 'l', 'j', '\x3', '\x2', '\x2', '\x2', 
		'm', 'p', '\x3', '\x2', '\x2', '\x2', 'n', 'l', '\x3', '\x2', '\x2', '\x2', 
		'n', 'o', '\x3', '\x2', '\x2', '\x2', 'o', 'r', '\x3', '\x2', '\x2', '\x2', 
		'p', 'n', '\x3', '\x2', '\x2', '\x2', 'q', '\x62', '\x3', '\x2', '\x2', 
		'\x2', 'q', 'r', '\x3', '\x2', '\x2', '\x2', 'r', '~', '\x3', '\x2', '\x2', 
		'\x2', 's', 'x', '\x5', '\b', '\x5', '\x2', 't', 'u', '\a', '\x14', '\x2', 
		'\x2', 'u', 'w', '\x5', '\b', '\x5', '\x2', 'v', 't', '\x3', '\x2', '\x2', 
		'\x2', 'w', 'z', '\x3', '\x2', '\x2', '\x2', 'x', 'v', '\x3', '\x2', '\x2', 
		'\x2', 'x', 'y', '\x3', '\x2', '\x2', '\x2', 'y', '|', '\x3', '\x2', '\x2', 
		'\x2', 'z', 'x', '\x3', '\x2', '\x2', '\x2', '{', 's', '\x3', '\x2', '\x2', 
		'\x2', '{', '|', '\x3', '\x2', '\x2', '\x2', '|', '~', '\x3', '\x2', '\x2', 
		'\x2', '}', 'q', '\x3', '\x2', '\x2', '\x2', '}', '{', '\x3', '\x2', '\x2', 
		'\x2', '~', '\x17', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x80', '\a', 
		'\x1B', '\x2', '\x2', '\x80', '\x81', '\x5', ' ', '\x11', '\x2', '\x81', 
		'\x84', '\x5', '\x4', '\x3', '\x2', '\x82', '\x83', '\a', '\x1C', '\x2', 
		'\x2', '\x83', '\x85', '\x5', '\x1A', '\xE', '\x2', '\x84', '\x82', '\x3', 
		'\x2', '\x2', '\x2', '\x84', '\x85', '\x3', '\x2', '\x2', '\x2', '\x85', 
		'\x19', '\x3', '\x2', '\x2', '\x2', '\x86', '\x89', '\x5', '\x18', '\r', 
		'\x2', '\x87', '\x89', '\x5', '\x4', '\x3', '\x2', '\x88', '\x86', '\x3', 
		'\x2', '\x2', '\x2', '\x88', '\x87', '\x3', '\x2', '\x2', '\x2', '\x89', 
		'\x1B', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\a', ' ', '\x2', 
		'\x2', '\x8B', '\x8C', '\x5', '\b', '\x5', '\x2', '\x8C', '\x8D', '\a', 
		'!', '\x2', '\x2', '\x8D', '\x90', '\x5', ' ', '\x11', '\x2', '\x8E', 
		'\x8F', '\a', '\"', '\x2', '\x2', '\x8F', '\x91', '\a', '%', '\x2', '\x2', 
		'\x90', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x90', '\x91', '\x3', '\x2', 
		'\x2', '\x2', '\x91', '\x92', '\x3', '\x2', '\x2', '\x2', '\x92', '\x93', 
		'\a', '\x1D', '\x2', '\x2', '\x93', '\x94', '\x5', '\x1E', '\x10', '\x2', 
		'\x94', '\x95', '\a', '\x1E', '\x2', '\x2', '\x95', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x96', '\x9A', '\x5', '\x6', '\x4', '\x2', '\x97', '\x9A', 
		'\a', '#', '\x2', '\x2', '\x98', '\x9A', '\a', '$', '\x2', '\x2', '\x99', 
		'\x96', '\x3', '\x2', '\x2', '\x2', '\x99', '\x97', '\x3', '\x2', '\x2', 
		'\x2', '\x99', '\x98', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x9B', '\x3', 
		'\x2', '\x2', '\x2', '\x9B', '\x99', '\x3', '\x2', '\x2', '\x2', '\x9B', 
		'\x9C', '\x3', '\x2', '\x2', '\x2', '\x9C', '\x1F', '\x3', '\x2', '\x2', 
		'\x2', '\x9D', '\x9E', '\b', '\x11', '\x1', '\x2', '\x9E', '\x9F', '\a', 
		'\x10', '\x2', '\x2', '\x9F', '\xAD', '\x5', ' ', '\x11', '\xF', '\xA0', 
		'\xA1', '\a', '\b', '\x2', '\x2', '\xA1', '\xAD', '\x5', ' ', '\x11', 
		'\xE', '\xA2', '\xAD', '\x5', '\"', '\x12', '\x2', '\xA3', '\xAD', '\x5', 
		'\x14', '\v', '\x2', '\xA4', '\xA7', '\x5', '$', '\x13', '\x2', '\xA5', 
		'\xA7', '\a', '*', '\x2', '\x2', '\xA6', '\xA4', '\x3', '\x2', '\x2', 
		'\x2', '\xA6', '\xA5', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xAD', '\x3', 
		'\x2', '\x2', '\x2', '\xA8', '\xA9', '\a', '\x16', '\x2', '\x2', '\xA9', 
		'\xAA', '\x5', ' ', '\x11', '\x2', '\xAA', '\xAB', '\a', '\x17', '\x2', 
		'\x2', '\xAB', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xAC', '\x9D', '\x3', 
		'\x2', '\x2', '\x2', '\xAC', '\xA0', '\x3', '\x2', '\x2', '\x2', '\xAC', 
		'\xA2', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xA3', '\x3', '\x2', '\x2', 
		'\x2', '\xAC', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xA8', '\x3', 
		'\x2', '\x2', '\x2', '\xAD', '\xC8', '\x3', '\x2', '\x2', '\x2', '\xAE', 
		'\xAF', '\f', '\r', '\x2', '\x2', '\xAF', '\xB0', '\t', '\x2', '\x2', 
		'\x2', '\xB0', '\xC7', '\x5', ' ', '\x11', '\xE', '\xB1', '\xB2', '\f', 
		'\f', '\x2', '\x2', '\xB2', '\xB3', '\t', '\x3', '\x2', '\x2', '\xB3', 
		'\xC7', '\x5', ' ', '\x11', '\r', '\xB4', '\xB5', '\f', '\v', '\x2', '\x2', 
		'\xB5', '\xB6', '\t', '\x4', '\x2', '\x2', '\xB6', '\xC7', '\x5', ' ', 
		'\x11', '\f', '\xB7', '\xB8', '\f', '\n', '\x2', '\x2', '\xB8', '\xB9', 
		'\t', '\x5', '\x2', '\x2', '\xB9', '\xC7', '\x5', ' ', '\x11', '\v', '\xBA', 
		'\xBB', '\f', '\t', '\x2', '\x2', '\xBB', '\xBC', '\a', '\a', '\x2', '\x2', 
		'\xBC', '\xC7', '\x5', ' ', '\x11', '\n', '\xBD', '\xBE', '\f', '\b', 
		'\x2', '\x2', '\xBE', '\xBF', '\a', '\x6', '\x2', '\x2', '\xBF', '\xC7', 
		'\x5', ' ', '\x11', '\t', '\xC0', '\xC1', '\f', '\a', '\x2', '\x2', '\xC1', 
		'\xC2', '\a', '\x4', '\x2', '\x2', '\xC2', '\xC3', '\x5', ' ', '\x11', 
		'\x2', '\xC3', '\xC4', '\a', '\x5', '\x2', '\x2', '\xC4', '\xC5', '\x5', 
		' ', '\x11', '\b', '\xC5', '\xC7', '\x3', '\x2', '\x2', '\x2', '\xC6', 
		'\xAE', '\x3', '\x2', '\x2', '\x2', '\xC6', '\xB1', '\x3', '\x2', '\x2', 
		'\x2', '\xC6', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xC6', '\xB7', '\x3', 
		'\x2', '\x2', '\x2', '\xC6', '\xBA', '\x3', '\x2', '\x2', '\x2', '\xC6', 
		'\xBD', '\x3', '\x2', '\x2', '\x2', '\xC6', '\xC0', '\x3', '\x2', '\x2', 
		'\x2', '\xC7', '\xCA', '\x3', '\x2', '\x2', '\x2', '\xC8', '\xC6', '\x3', 
		'\x2', '\x2', '\x2', '\xC8', '\xC9', '\x3', '\x2', '\x2', '\x2', '\xC9', 
		'!', '\x3', '\x2', '\x2', '\x2', '\xCA', '\xC8', '\x3', '\x2', '\x2', 
		'\x2', '\xCB', '\xD2', '\a', '%', '\x2', '\x2', '\xCC', '\xD2', '\a', 
		'&', '\x2', '\x2', '\xCD', '\xD2', '\a', '(', '\x2', '\x2', '\xCE', '\xD2', 
		'\a', '\'', '\x2', '\x2', '\xCF', '\xD2', '\a', ')', '\x2', '\x2', '\xD0', 
		'\xD2', '\a', '\x3', '\x2', '\x2', '\xD1', '\xCB', '\x3', '\x2', '\x2', 
		'\x2', '\xD1', '\xCC', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xCD', '\x3', 
		'\x2', '\x2', '\x2', '\xD1', '\xCE', '\x3', '\x2', '\x2', '\x2', '\xD1', 
		'\xCF', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xD0', '\x3', '\x2', '\x2', 
		'\x2', '\xD2', '#', '\x3', '\x2', '\x2', '\x2', '\xD3', '\xD4', '\a', 
		'*', '\x2', '\x2', '\xD4', '\xD5', '\a', '\x18', '\x2', '\x2', '\xD5', 
		'\xD6', '\x5', ' ', '\x11', '\x2', '\xD6', '\xD7', '\a', '\x19', '\x2', 
		'\x2', '\xD7', '%', '\x3', '\x2', '\x2', '\x2', '\x19', ')', '/', '\x39', 
		'\x46', 'T', 'W', '[', 'g', 'n', 'q', 'x', '{', '}', '\x84', '\x88', '\x90', 
		'\x99', '\x9B', '\xA6', '\xAC', '\xC6', '\xC8', '\xD1',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
