//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from PineScript.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class PineScriptParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		COND=1, COND_ELSE=2, OR=3, AND=4, NOT=5, EQ=6, NEQ=7, GT=8, GE=9, LT=10, 
		LE=11, PLUS=12, MINUS=13, MUL=14, DIV=15, MOD=16, COMMA=17, ARROW=18, 
		LPAR=19, RPAR=20, LSQBR=21, RSQBR=22, DEFINE=23, IF_COND=24, IF_COND_ELSE=25, 
		BEGIN=26, END=27, ASSIGN=28, FOR_STMT=29, FOR_STMT_TO=30, FOR_STMT_BY=31, 
		BREAK=32, CONTINUE=33, LBEG=34, LEND=35, PLEND=36, INT_LITERAL=37, FLOAT_LITERAL=38, 
		STR_LITERAL=39, BOOL_LITERAL=40, COLOR_LITERAL=41, ID=42, ID_EX=43, INDENT=44, 
		LINE_CONTINUATION=45, EMPTY_LINE_V1=46, EMPTY_LINE=47, WHITESPACE=48, 
		Tokens=49;
	public const int
		RULE_script = 0, RULE_block = 1, RULE_statement = 2, RULE_variableDeclaration = 3, 
		RULE_variableAssignment = 4, RULE_variableValue = 5, RULE_functionDeclaration = 6, 
		RULE_functionParameters = 7, RULE_functionBody = 8, RULE_functionCall = 9, 
		RULE_functionArguments = 10, RULE_conditional = 11, RULE_loop = 12, RULE_loopBody = 13, 
		RULE_expression = 14, RULE_seriesAccess = 15;
	public static readonly string[] ruleNames = {
		"script", "block", "statement", "variableDeclaration", "variableAssignment", 
		"variableValue", "functionDeclaration", "functionParameters", "functionBody", 
		"functionCall", "functionArguments", "conditional", "loop", "loopBody", 
		"expression", "seriesAccess"
	};

	private static readonly string[] _LiteralNames = {
		null, "'?'", "':'", "'or'", "'and'", "'not'", "'=='", "'!='", "'>'", "'>='", 
		"'<'", "'<='", "'+'", "'-'", "'*'", "'/'", "'%'", "','", "'=>'", "'('", 
		"')'", "'['", "']'", "'='", "'if'", "'else'", "'|BEGIN|'", "'|END|'", 
		"':='", "'for'", "'to'", "'by'", "'break'", "'continue'", "'|B|'", "'|E|'", 
		"'|PE|'", null, null, null, null, null, null, null, "'|INDENT|'", "'|C|'", 
		"'|EMPTY_V1|'", "'|EMPTY|'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "COND", "COND_ELSE", "OR", "AND", "NOT", "EQ", "NEQ", "GT", "GE", 
		"LT", "LE", "PLUS", "MINUS", "MUL", "DIV", "MOD", "COMMA", "ARROW", "LPAR", 
		"RPAR", "LSQBR", "RSQBR", "DEFINE", "IF_COND", "IF_COND_ELSE", "BEGIN", 
		"END", "ASSIGN", "FOR_STMT", "FOR_STMT_TO", "FOR_STMT_BY", "BREAK", "CONTINUE", 
		"LBEG", "LEND", "PLEND", "INT_LITERAL", "FLOAT_LITERAL", "STR_LITERAL", 
		"BOOL_LITERAL", "COLOR_LITERAL", "ID", "ID_EX", "INDENT", "LINE_CONTINUATION", 
		"EMPTY_LINE_V1", "EMPTY_LINE", "WHITESPACE", "Tokens"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "PineScript.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static PineScriptParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public PineScriptParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public PineScriptParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ScriptContext : ParserRuleContext {
		public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ScriptContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_script; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterScript(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitScript(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitScript(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ScriptContext script() {
		ScriptContext _localctx = new ScriptContext(Context, State);
		EnterRule(_localctx, 0, RULE_script);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 33;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 32; statement();
				}
				}
				State = 35;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << IF_COND) | (1L << FOR_STMT) | (1L << ID))) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockContext : ParserRuleContext {
		public ITerminalNode BEGIN() { return GetToken(PineScriptParser.BEGIN, 0); }
		public ITerminalNode END() { return GetToken(PineScriptParser.END, 0); }
		public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public BlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_block; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterBlock(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitBlock(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockContext block() {
		BlockContext _localctx = new BlockContext(Context, State);
		EnterRule(_localctx, 2, RULE_block);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 37; Match(BEGIN);
			State = 39;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 38; statement();
				}
				}
				State = 41;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << IF_COND) | (1L << FOR_STMT) | (1L << ID))) != 0) );
			State = 43; Match(END);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		public VariableDeclarationContext variableDeclaration() {
			return GetRuleContext<VariableDeclarationContext>(0);
		}
		public VariableAssignmentContext variableAssignment() {
			return GetRuleContext<VariableAssignmentContext>(0);
		}
		public FunctionDeclarationContext functionDeclaration() {
			return GetRuleContext<FunctionDeclarationContext>(0);
		}
		public FunctionCallContext functionCall() {
			return GetRuleContext<FunctionCallContext>(0);
		}
		public ConditionalContext conditional() {
			return GetRuleContext<ConditionalContext>(0);
		}
		public LoopContext loop() {
			return GetRuleContext<LoopContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 4, RULE_statement);
		try {
			State = 51;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 45; variableDeclaration();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 46; variableAssignment();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 47; functionDeclaration();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 48; functionCall();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 49; conditional();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 50; loop();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableDeclarationContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(PineScriptParser.ID, 0); }
		public ITerminalNode DEFINE() { return GetToken(PineScriptParser.DEFINE, 0); }
		public VariableValueContext variableValue() {
			return GetRuleContext<VariableValueContext>(0);
		}
		public VariableDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variableDeclaration; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterVariableDeclaration(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitVariableDeclaration(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableDeclarationContext variableDeclaration() {
		VariableDeclarationContext _localctx = new VariableDeclarationContext(Context, State);
		EnterRule(_localctx, 6, RULE_variableDeclaration);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 53; Match(ID);
			State = 54; Match(DEFINE);
			State = 55; variableValue();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableAssignmentContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(PineScriptParser.ID, 0); }
		public ITerminalNode ASSIGN() { return GetToken(PineScriptParser.ASSIGN, 0); }
		public VariableValueContext variableValue() {
			return GetRuleContext<VariableValueContext>(0);
		}
		public VariableAssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variableAssignment; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterVariableAssignment(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitVariableAssignment(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableAssignment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableAssignmentContext variableAssignment() {
		VariableAssignmentContext _localctx = new VariableAssignmentContext(Context, State);
		EnterRule(_localctx, 8, RULE_variableAssignment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 57; Match(ID);
			State = 58; Match(ASSIGN);
			State = 59; variableValue();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableValueContext : ParserRuleContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ConditionalContext conditional() {
			return GetRuleContext<ConditionalContext>(0);
		}
		public LoopContext loop() {
			return GetRuleContext<LoopContext>(0);
		}
		public VariableValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variableValue; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterVariableValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitVariableValue(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableValueContext variableValue() {
		VariableValueContext _localctx = new VariableValueContext(Context, State);
		EnterRule(_localctx, 10, RULE_variableValue);
		try {
			State = 64;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NOT:
			case MINUS:
			case LPAR:
			case INT_LITERAL:
			case FLOAT_LITERAL:
			case STR_LITERAL:
			case BOOL_LITERAL:
			case COLOR_LITERAL:
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 61; expression(0);
				}
				break;
			case IF_COND:
				EnterOuterAlt(_localctx, 2);
				{
				State = 62; conditional();
				}
				break;
			case FOR_STMT:
				EnterOuterAlt(_localctx, 3);
				{
				State = 63; loop();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionDeclarationContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(PineScriptParser.ID, 0); }
		public ITerminalNode LPAR() { return GetToken(PineScriptParser.LPAR, 0); }
		public FunctionParametersContext functionParameters() {
			return GetRuleContext<FunctionParametersContext>(0);
		}
		public ITerminalNode RPAR() { return GetToken(PineScriptParser.RPAR, 0); }
		public ITerminalNode ARROW() { return GetToken(PineScriptParser.ARROW, 0); }
		public FunctionBodyContext functionBody() {
			return GetRuleContext<FunctionBodyContext>(0);
		}
		public FunctionDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionDeclaration; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterFunctionDeclaration(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitFunctionDeclaration(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionDeclarationContext functionDeclaration() {
		FunctionDeclarationContext _localctx = new FunctionDeclarationContext(Context, State);
		EnterRule(_localctx, 12, RULE_functionDeclaration);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 66; Match(ID);
			State = 67; Match(LPAR);
			State = 68; functionParameters();
			State = 69; Match(RPAR);
			State = 70; Match(ARROW);
			State = 71; functionBody();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionParametersContext : ParserRuleContext {
		public ITerminalNode[] ID() { return GetTokens(PineScriptParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(PineScriptParser.ID, i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(PineScriptParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(PineScriptParser.COMMA, i);
		}
		public FunctionParametersContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionParameters; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterFunctionParameters(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitFunctionParameters(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionParameters(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionParametersContext functionParameters() {
		FunctionParametersContext _localctx = new FunctionParametersContext(Context, State);
		EnterRule(_localctx, 14, RULE_functionParameters);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 81;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ID) {
				{
				State = 73; Match(ID);
				State = 78;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 74; Match(COMMA);
					State = 75; Match(ID);
					}
					}
					State = 80;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionBodyContext : ParserRuleContext {
		public BlockContext block() {
			return GetRuleContext<BlockContext>(0);
		}
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public FunctionBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionBody; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterFunctionBody(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitFunctionBody(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionBody(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionBodyContext functionBody() {
		FunctionBodyContext _localctx = new FunctionBodyContext(Context, State);
		EnterRule(_localctx, 16, RULE_functionBody);
		try {
			State = 85;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case BEGIN:
				EnterOuterAlt(_localctx, 1);
				{
				State = 83; block();
				}
				break;
			case NOT:
			case MINUS:
			case LPAR:
			case INT_LITERAL:
			case FLOAT_LITERAL:
			case STR_LITERAL:
			case BOOL_LITERAL:
			case COLOR_LITERAL:
			case ID:
				EnterOuterAlt(_localctx, 2);
				{
				State = 84; expression(0);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionCallContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(PineScriptParser.ID, 0); }
		public ITerminalNode LPAR() { return GetToken(PineScriptParser.LPAR, 0); }
		public FunctionArgumentsContext functionArguments() {
			return GetRuleContext<FunctionArgumentsContext>(0);
		}
		public ITerminalNode RPAR() { return GetToken(PineScriptParser.RPAR, 0); }
		public FunctionCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionCall; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterFunctionCall(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitFunctionCall(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionCallContext functionCall() {
		FunctionCallContext _localctx = new FunctionCallContext(Context, State);
		EnterRule(_localctx, 18, RULE_functionCall);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 87; Match(ID);
			State = 88; Match(LPAR);
			State = 89; functionArguments();
			State = 90; Match(RPAR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionArgumentsContext : ParserRuleContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(PineScriptParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(PineScriptParser.COMMA, i);
		}
		public VariableDeclarationContext[] variableDeclaration() {
			return GetRuleContexts<VariableDeclarationContext>();
		}
		public VariableDeclarationContext variableDeclaration(int i) {
			return GetRuleContext<VariableDeclarationContext>(i);
		}
		public FunctionArgumentsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionArguments; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterFunctionArguments(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitFunctionArguments(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionArguments(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionArgumentsContext functionArguments() {
		FunctionArgumentsContext _localctx = new FunctionArgumentsContext(Context, State);
		EnterRule(_localctx, 20, RULE_functionArguments);
		int _la;
		try {
			int _alt;
			State = 119;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 107;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << NOT) | (1L << MINUS) | (1L << LPAR) | (1L << INT_LITERAL) | (1L << FLOAT_LITERAL) | (1L << STR_LITERAL) | (1L << BOOL_LITERAL) | (1L << COLOR_LITERAL) | (1L << ID))) != 0)) {
					{
					State = 92; expression(0);
					State = 97;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,7,Context);
					while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
						if ( _alt==1 ) {
							{
							{
							State = 93; Match(COMMA);
							State = 94; expression(0);
							}
							} 
						}
						State = 99;
						ErrorHandler.Sync(this);
						_alt = Interpreter.AdaptivePredict(TokenStream,7,Context);
					}
					State = 104;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==COMMA) {
						{
						{
						State = 100; Match(COMMA);
						State = 101; variableDeclaration();
						}
						}
						State = 106;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 117;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==ID) {
					{
					State = 109; variableDeclaration();
					State = 114;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==COMMA) {
						{
						{
						State = 110; Match(COMMA);
						State = 111; variableDeclaration();
						}
						}
						State = 116;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConditionalContext : ParserRuleContext {
		public ITerminalNode IF_COND() { return GetToken(PineScriptParser.IF_COND, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public BlockContext[] block() {
			return GetRuleContexts<BlockContext>();
		}
		public BlockContext block(int i) {
			return GetRuleContext<BlockContext>(i);
		}
		public ITerminalNode IF_COND_ELSE() { return GetToken(PineScriptParser.IF_COND_ELSE, 0); }
		public ConditionalContext conditional() {
			return GetRuleContext<ConditionalContext>(0);
		}
		public ConditionalContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_conditional; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterConditional(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitConditional(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConditional(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConditionalContext conditional() {
		ConditionalContext _localctx = new ConditionalContext(Context, State);
		EnterRule(_localctx, 22, RULE_conditional);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 121; Match(IF_COND);
			State = 122; expression(0);
			State = 123; block();
			State = 128;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				{
				State = 124; Match(IF_COND_ELSE);
				State = 125; conditional();
				}
				break;
			case 2:
				{
				State = 126; Match(IF_COND_ELSE);
				State = 127; block();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LoopContext : ParserRuleContext {
		public ITerminalNode FOR_STMT() { return GetToken(PineScriptParser.FOR_STMT, 0); }
		public VariableDeclarationContext variableDeclaration() {
			return GetRuleContext<VariableDeclarationContext>(0);
		}
		public ITerminalNode FOR_STMT_TO() { return GetToken(PineScriptParser.FOR_STMT_TO, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public LoopBodyContext loopBody() {
			return GetRuleContext<LoopBodyContext>(0);
		}
		public ITerminalNode FOR_STMT_BY() { return GetToken(PineScriptParser.FOR_STMT_BY, 0); }
		public ITerminalNode INT_LITERAL() { return GetToken(PineScriptParser.INT_LITERAL, 0); }
		public LoopContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_loop; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterLoop(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitLoop(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLoop(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LoopContext loop() {
		LoopContext _localctx = new LoopContext(Context, State);
		EnterRule(_localctx, 24, RULE_loop);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 130; Match(FOR_STMT);
			State = 131; variableDeclaration();
			State = 132; Match(FOR_STMT_TO);
			State = 133; expression(0);
			State = 136;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==FOR_STMT_BY) {
				{
				State = 134; Match(FOR_STMT_BY);
				State = 135; Match(INT_LITERAL);
				}
			}

			State = 138; loopBody();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LoopBodyContext : ParserRuleContext {
		public ITerminalNode BEGIN() { return GetToken(PineScriptParser.BEGIN, 0); }
		public ITerminalNode END() { return GetToken(PineScriptParser.END, 0); }
		public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ITerminalNode[] BREAK() { return GetTokens(PineScriptParser.BREAK); }
		public ITerminalNode BREAK(int i) {
			return GetToken(PineScriptParser.BREAK, i);
		}
		public ITerminalNode[] CONTINUE() { return GetTokens(PineScriptParser.CONTINUE); }
		public ITerminalNode CONTINUE(int i) {
			return GetToken(PineScriptParser.CONTINUE, i);
		}
		public LoopBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_loopBody; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterLoopBody(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitLoopBody(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLoopBody(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LoopBodyContext loopBody() {
		LoopBodyContext _localctx = new LoopBodyContext(Context, State);
		EnterRule(_localctx, 26, RULE_loopBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 140; Match(BEGIN);
			State = 144;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				State = 144;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case IF_COND:
				case FOR_STMT:
				case ID:
					{
					State = 141; statement();
					}
					break;
				case BREAK:
					{
					State = 142; Match(BREAK);
					}
					break;
				case CONTINUE:
					{
					State = 143; Match(CONTINUE);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 146;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << IF_COND) | (1L << FOR_STMT) | (1L << BREAK) | (1L << CONTINUE) | (1L << ID))) != 0) );
			State = 148; Match(END);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
	 
		public ExpressionContext() { }
		public virtual void CopyFrom(ExpressionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class TernaryExpressionContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode COND() { return GetToken(PineScriptParser.COND, 0); }
		public ITerminalNode COND_ELSE() { return GetToken(PineScriptParser.COND_ELSE, 0); }
		public TernaryExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterTernaryExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitTernaryExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTernaryExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ColorExpressionContext : ExpressionContext {
		public ITerminalNode COLOR_LITERAL() { return GetToken(PineScriptParser.COLOR_LITERAL, 0); }
		public ColorExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterColorExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitColorExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitColorExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class UnaryMinusExpressionContext : ExpressionContext {
		public ITerminalNode MINUS() { return GetToken(PineScriptParser.MINUS, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public UnaryMinusExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterUnaryMinusExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitUnaryMinusExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryMinusExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BinaryOperationExpressionContext : ExpressionContext {
		public IToken op;
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode MUL() { return GetToken(PineScriptParser.MUL, 0); }
		public ITerminalNode DIV() { return GetToken(PineScriptParser.DIV, 0); }
		public ITerminalNode MOD() { return GetToken(PineScriptParser.MOD, 0); }
		public ITerminalNode PLUS() { return GetToken(PineScriptParser.PLUS, 0); }
		public ITerminalNode MINUS() { return GetToken(PineScriptParser.MINUS, 0); }
		public ITerminalNode GE() { return GetToken(PineScriptParser.GE, 0); }
		public ITerminalNode LE() { return GetToken(PineScriptParser.LE, 0); }
		public ITerminalNode GT() { return GetToken(PineScriptParser.GT, 0); }
		public ITerminalNode LT() { return GetToken(PineScriptParser.LT, 0); }
		public ITerminalNode EQ() { return GetToken(PineScriptParser.EQ, 0); }
		public ITerminalNode NEQ() { return GetToken(PineScriptParser.NEQ, 0); }
		public ITerminalNode AND() { return GetToken(PineScriptParser.AND, 0); }
		public ITerminalNode OR() { return GetToken(PineScriptParser.OR, 0); }
		public BinaryOperationExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterBinaryOperationExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitBinaryOperationExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBinaryOperationExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IntExpressionContext : ExpressionContext {
		public ITerminalNode INT_LITERAL() { return GetToken(PineScriptParser.INT_LITERAL, 0); }
		public IntExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterIntExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitIntExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIntExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class StringExpressionContext : ExpressionContext {
		public ITerminalNode STR_LITERAL() { return GetToken(PineScriptParser.STR_LITERAL, 0); }
		public StringExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterStringExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitStringExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStringExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NotExpressionContext : ExpressionContext {
		public ITerminalNode NOT() { return GetToken(PineScriptParser.NOT, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public NotExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterNotExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitNotExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNotExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FloatExpressionContext : ExpressionContext {
		public ITerminalNode FLOAT_LITERAL() { return GetToken(PineScriptParser.FLOAT_LITERAL, 0); }
		public FloatExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterFloatExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitFloatExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFloatExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class GroupExpressionContext : ExpressionContext {
		public ITerminalNode LPAR() { return GetToken(PineScriptParser.LPAR, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ITerminalNode RPAR() { return GetToken(PineScriptParser.RPAR, 0); }
		public GroupExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterGroupExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitGroupExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGroupExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionCallExpressionContext : ExpressionContext {
		public FunctionCallContext functionCall() {
			return GetRuleContext<FunctionCallContext>(0);
		}
		public FunctionCallExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterFunctionCallExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitFunctionCallExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionCallExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BoolExpressionContext : ExpressionContext {
		public ITerminalNode BOOL_LITERAL() { return GetToken(PineScriptParser.BOOL_LITERAL, 0); }
		public BoolExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterBoolExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitBoolExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBoolExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IdentifierExpressionContext : ExpressionContext {
		public SeriesAccessContext seriesAccess() {
			return GetRuleContext<SeriesAccessContext>(0);
		}
		public ITerminalNode ID() { return GetToken(PineScriptParser.ID, 0); }
		public IdentifierExpressionContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterIdentifierExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitIdentifierExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdentifierExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		return expression(0);
	}

	private ExpressionContext expression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExpressionContext _localctx = new ExpressionContext(Context, _parentState);
		ExpressionContext _prevctx = _localctx;
		int _startState = 28;
		EnterRecursionRule(_localctx, 28, RULE_expression, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 169;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,18,Context) ) {
			case 1:
				{
				_localctx = new UnaryMinusExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 151; Match(MINUS);
				State = 152; expression(17);
				}
				break;
			case 2:
				{
				_localctx = new NotExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 153; Match(NOT);
				State = 154; expression(16);
				}
				break;
			case 3:
				{
				_localctx = new IntExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 155; Match(INT_LITERAL);
				}
				break;
			case 4:
				{
				_localctx = new FloatExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 156; Match(FLOAT_LITERAL);
				}
				break;
			case 5:
				{
				_localctx = new BoolExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 157; Match(BOOL_LITERAL);
				}
				break;
			case 6:
				{
				_localctx = new StringExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 158; Match(STR_LITERAL);
				}
				break;
			case 7:
				{
				_localctx = new ColorExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 159; Match(COLOR_LITERAL);
				}
				break;
			case 8:
				{
				_localctx = new FunctionCallExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 160; functionCall();
				}
				break;
			case 9:
				{
				_localctx = new IdentifierExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 163;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,17,Context) ) {
				case 1:
					{
					State = 161; seriesAccess();
					}
					break;
				case 2:
					{
					State = 162; Match(ID);
					}
					break;
				}
				}
				break;
			case 10:
				{
				_localctx = new GroupExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 165; Match(LPAR);
				State = 166; expression(0);
				State = 167; Match(RPAR);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 197;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,20,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 195;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,19,Context) ) {
					case 1:
						{
						_localctx = new BinaryOperationExpressionContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 171;
						if (!(Precpred(Context, 15))) throw new FailedPredicateException(this, "Precpred(Context, 15)");
						State = 172;
						((BinaryOperationExpressionContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << MUL) | (1L << DIV) | (1L << MOD))) != 0)) ) {
							((BinaryOperationExpressionContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 173; expression(16);
						}
						break;
					case 2:
						{
						_localctx = new BinaryOperationExpressionContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 174;
						if (!(Precpred(Context, 14))) throw new FailedPredicateException(this, "Precpred(Context, 14)");
						State = 175;
						((BinaryOperationExpressionContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==PLUS || _la==MINUS) ) {
							((BinaryOperationExpressionContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 176; expression(15);
						}
						break;
					case 3:
						{
						_localctx = new BinaryOperationExpressionContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 177;
						if (!(Precpred(Context, 13))) throw new FailedPredicateException(this, "Precpred(Context, 13)");
						State = 178;
						((BinaryOperationExpressionContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << GT) | (1L << GE) | (1L << LT) | (1L << LE))) != 0)) ) {
							((BinaryOperationExpressionContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 179; expression(14);
						}
						break;
					case 4:
						{
						_localctx = new BinaryOperationExpressionContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 180;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 181;
						((BinaryOperationExpressionContext)_localctx).op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==EQ || _la==NEQ) ) {
							((BinaryOperationExpressionContext)_localctx).op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 182; expression(13);
						}
						break;
					case 5:
						{
						_localctx = new BinaryOperationExpressionContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 183;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 184; ((BinaryOperationExpressionContext)_localctx).op = Match(AND);
						State = 185; expression(12);
						}
						break;
					case 6:
						{
						_localctx = new BinaryOperationExpressionContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 186;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 187; ((BinaryOperationExpressionContext)_localctx).op = Match(OR);
						State = 188; expression(11);
						}
						break;
					case 7:
						{
						_localctx = new TernaryExpressionContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 189;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 190; Match(COND);
						State = 191; expression(0);
						State = 192; Match(COND_ELSE);
						State = 193; expression(10);
						}
						break;
					}
					} 
				}
				State = 199;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,20,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class SeriesAccessContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(PineScriptParser.ID, 0); }
		public ITerminalNode LSQBR() { return GetToken(PineScriptParser.LSQBR, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ITerminalNode RSQBR() { return GetToken(PineScriptParser.RSQBR, 0); }
		public SeriesAccessContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_seriesAccess; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.EnterSeriesAccess(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPineScriptListener typedListener = listener as IPineScriptListener;
			if (typedListener != null) typedListener.ExitSeriesAccess(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPineScriptVisitor<TResult> typedVisitor = visitor as IPineScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSeriesAccess(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SeriesAccessContext seriesAccess() {
		SeriesAccessContext _localctx = new SeriesAccessContext(Context, State);
		EnterRule(_localctx, 30, RULE_seriesAccess);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 200; Match(ID);
			State = 201; Match(LSQBR);
			State = 202; expression(0);
			State = 203; Match(RSQBR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 14: return expression_sempred((ExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expression_sempred(ExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 15);
		case 1: return Precpred(Context, 14);
		case 2: return Precpred(Context, 13);
		case 3: return Precpred(Context, 12);
		case 4: return Precpred(Context, 11);
		case 5: return Precpred(Context, 10);
		case 6: return Precpred(Context, 9);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x33', '\xD0', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x3', '\x2', '\x6', '\x2', '$', '\n', '\x2', '\r', 
		'\x2', '\xE', '\x2', '%', '\x3', '\x3', '\x3', '\x3', '\x6', '\x3', '*', 
		'\n', '\x3', '\r', '\x3', '\xE', '\x3', '+', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x5', '\x4', '\x36', '\n', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x5', '\a', 
		'\x43', '\n', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\a', '\t', 'O', '\n', '\t', '\f', '\t', '\xE', '\t', 'R', '\v', 
		'\t', '\x5', '\t', 'T', '\n', '\t', '\x3', '\n', '\x3', '\n', '\x5', '\n', 
		'X', '\n', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\a', '\f', '\x62', '\n', 
		'\f', '\f', '\f', '\xE', '\f', '\x65', '\v', '\f', '\x3', '\f', '\x3', 
		'\f', '\a', '\f', 'i', '\n', '\f', '\f', '\f', '\xE', '\f', 'l', '\v', 
		'\f', '\x5', '\f', 'n', '\n', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\a', '\f', 's', '\n', '\f', '\f', '\f', '\xE', '\f', 'v', '\v', '\f', 
		'\x5', '\f', 'x', '\n', '\f', '\x5', '\f', 'z', '\n', '\f', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x5', '\r', '\x83', '\n', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x5', '\xE', '\x8B', 
		'\n', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x6', '\xF', '\x93', '\n', '\xF', '\r', '\xF', '\xE', 
		'\xF', '\x94', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x5', '\x10', '\xA6', '\n', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x5', '\x10', '\xAC', '\n', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\a', '\x10', 
		'\xC6', '\n', '\x10', '\f', '\x10', '\xE', '\x10', '\xC9', '\v', '\x10', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x2', '\x3', '\x1E', '\x12', '\x2', '\x4', '\x6', '\b', 
		'\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', '\x18', '\x1A', '\x1C', 
		'\x1E', ' ', '\x2', '\x6', '\x3', '\x2', '\x10', '\x12', '\x3', '\x2', 
		'\xE', '\xF', '\x3', '\x2', '\n', '\r', '\x3', '\x2', '\b', '\t', '\x2', 
		'\xE8', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x4', '\'', '\x3', '\x2', 
		'\x2', '\x2', '\x6', '\x35', '\x3', '\x2', '\x2', '\x2', '\b', '\x37', 
		'\x3', '\x2', '\x2', '\x2', '\n', ';', '\x3', '\x2', '\x2', '\x2', '\f', 
		'\x42', '\x3', '\x2', '\x2', '\x2', '\xE', '\x44', '\x3', '\x2', '\x2', 
		'\x2', '\x10', 'S', '\x3', '\x2', '\x2', '\x2', '\x12', 'W', '\x3', '\x2', 
		'\x2', '\x2', '\x14', 'Y', '\x3', '\x2', '\x2', '\x2', '\x16', 'y', '\x3', 
		'\x2', '\x2', '\x2', '\x18', '{', '\x3', '\x2', '\x2', '\x2', '\x1A', 
		'\x84', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x8E', '\x3', '\x2', '\x2', 
		'\x2', '\x1E', '\xAB', '\x3', '\x2', '\x2', '\x2', ' ', '\xCA', '\x3', 
		'\x2', '\x2', '\x2', '\"', '$', '\x5', '\x6', '\x4', '\x2', '#', '\"', 
		'\x3', '\x2', '\x2', '\x2', '$', '%', '\x3', '\x2', '\x2', '\x2', '%', 
		'#', '\x3', '\x2', '\x2', '\x2', '%', '&', '\x3', '\x2', '\x2', '\x2', 
		'&', '\x3', '\x3', '\x2', '\x2', '\x2', '\'', ')', '\a', '\x1C', '\x2', 
		'\x2', '(', '*', '\x5', '\x6', '\x4', '\x2', ')', '(', '\x3', '\x2', '\x2', 
		'\x2', '*', '+', '\x3', '\x2', '\x2', '\x2', '+', ')', '\x3', '\x2', '\x2', 
		'\x2', '+', ',', '\x3', '\x2', '\x2', '\x2', ',', '-', '\x3', '\x2', '\x2', 
		'\x2', '-', '.', '\a', '\x1D', '\x2', '\x2', '.', '\x5', '\x3', '\x2', 
		'\x2', '\x2', '/', '\x36', '\x5', '\b', '\x5', '\x2', '\x30', '\x36', 
		'\x5', '\n', '\x6', '\x2', '\x31', '\x36', '\x5', '\xE', '\b', '\x2', 
		'\x32', '\x36', '\x5', '\x14', '\v', '\x2', '\x33', '\x36', '\x5', '\x18', 
		'\r', '\x2', '\x34', '\x36', '\x5', '\x1A', '\xE', '\x2', '\x35', '/', 
		'\x3', '\x2', '\x2', '\x2', '\x35', '\x30', '\x3', '\x2', '\x2', '\x2', 
		'\x35', '\x31', '\x3', '\x2', '\x2', '\x2', '\x35', '\x32', '\x3', '\x2', 
		'\x2', '\x2', '\x35', '\x33', '\x3', '\x2', '\x2', '\x2', '\x35', '\x34', 
		'\x3', '\x2', '\x2', '\x2', '\x36', '\a', '\x3', '\x2', '\x2', '\x2', 
		'\x37', '\x38', '\a', ',', '\x2', '\x2', '\x38', '\x39', '\a', '\x19', 
		'\x2', '\x2', '\x39', ':', '\x5', '\f', '\a', '\x2', ':', '\t', '\x3', 
		'\x2', '\x2', '\x2', ';', '<', '\a', ',', '\x2', '\x2', '<', '=', '\a', 
		'\x1E', '\x2', '\x2', '=', '>', '\x5', '\f', '\a', '\x2', '>', '\v', '\x3', 
		'\x2', '\x2', '\x2', '?', '\x43', '\x5', '\x1E', '\x10', '\x2', '@', '\x43', 
		'\x5', '\x18', '\r', '\x2', '\x41', '\x43', '\x5', '\x1A', '\xE', '\x2', 
		'\x42', '?', '\x3', '\x2', '\x2', '\x2', '\x42', '@', '\x3', '\x2', '\x2', 
		'\x2', '\x42', '\x41', '\x3', '\x2', '\x2', '\x2', '\x43', '\r', '\x3', 
		'\x2', '\x2', '\x2', '\x44', '\x45', '\a', ',', '\x2', '\x2', '\x45', 
		'\x46', '\a', '\x15', '\x2', '\x2', '\x46', 'G', '\x5', '\x10', '\t', 
		'\x2', 'G', 'H', '\a', '\x16', '\x2', '\x2', 'H', 'I', '\a', '\x14', '\x2', 
		'\x2', 'I', 'J', '\x5', '\x12', '\n', '\x2', 'J', '\xF', '\x3', '\x2', 
		'\x2', '\x2', 'K', 'P', '\a', ',', '\x2', '\x2', 'L', 'M', '\a', '\x13', 
		'\x2', '\x2', 'M', 'O', '\a', ',', '\x2', '\x2', 'N', 'L', '\x3', '\x2', 
		'\x2', '\x2', 'O', 'R', '\x3', '\x2', '\x2', '\x2', 'P', 'N', '\x3', '\x2', 
		'\x2', '\x2', 'P', 'Q', '\x3', '\x2', '\x2', '\x2', 'Q', 'T', '\x3', '\x2', 
		'\x2', '\x2', 'R', 'P', '\x3', '\x2', '\x2', '\x2', 'S', 'K', '\x3', '\x2', 
		'\x2', '\x2', 'S', 'T', '\x3', '\x2', '\x2', '\x2', 'T', '\x11', '\x3', 
		'\x2', '\x2', '\x2', 'U', 'X', '\x5', '\x4', '\x3', '\x2', 'V', 'X', '\x5', 
		'\x1E', '\x10', '\x2', 'W', 'U', '\x3', '\x2', '\x2', '\x2', 'W', 'V', 
		'\x3', '\x2', '\x2', '\x2', 'X', '\x13', '\x3', '\x2', '\x2', '\x2', 'Y', 
		'Z', '\a', ',', '\x2', '\x2', 'Z', '[', '\a', '\x15', '\x2', '\x2', '[', 
		'\\', '\x5', '\x16', '\f', '\x2', '\\', ']', '\a', '\x16', '\x2', '\x2', 
		']', '\x15', '\x3', '\x2', '\x2', '\x2', '^', '\x63', '\x5', '\x1E', '\x10', 
		'\x2', '_', '`', '\a', '\x13', '\x2', '\x2', '`', '\x62', '\x5', '\x1E', 
		'\x10', '\x2', '\x61', '_', '\x3', '\x2', '\x2', '\x2', '\x62', '\x65', 
		'\x3', '\x2', '\x2', '\x2', '\x63', '\x61', '\x3', '\x2', '\x2', '\x2', 
		'\x63', '\x64', '\x3', '\x2', '\x2', '\x2', '\x64', 'j', '\x3', '\x2', 
		'\x2', '\x2', '\x65', '\x63', '\x3', '\x2', '\x2', '\x2', '\x66', 'g', 
		'\a', '\x13', '\x2', '\x2', 'g', 'i', '\x5', '\b', '\x5', '\x2', 'h', 
		'\x66', '\x3', '\x2', '\x2', '\x2', 'i', 'l', '\x3', '\x2', '\x2', '\x2', 
		'j', 'h', '\x3', '\x2', '\x2', '\x2', 'j', 'k', '\x3', '\x2', '\x2', '\x2', 
		'k', 'n', '\x3', '\x2', '\x2', '\x2', 'l', 'j', '\x3', '\x2', '\x2', '\x2', 
		'm', '^', '\x3', '\x2', '\x2', '\x2', 'm', 'n', '\x3', '\x2', '\x2', '\x2', 
		'n', 'z', '\x3', '\x2', '\x2', '\x2', 'o', 't', '\x5', '\b', '\x5', '\x2', 
		'p', 'q', '\a', '\x13', '\x2', '\x2', 'q', 's', '\x5', '\b', '\x5', '\x2', 
		'r', 'p', '\x3', '\x2', '\x2', '\x2', 's', 'v', '\x3', '\x2', '\x2', '\x2', 
		't', 'r', '\x3', '\x2', '\x2', '\x2', 't', 'u', '\x3', '\x2', '\x2', '\x2', 
		'u', 'x', '\x3', '\x2', '\x2', '\x2', 'v', 't', '\x3', '\x2', '\x2', '\x2', 
		'w', 'o', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\x3', '\x2', '\x2', '\x2', 
		'x', 'z', '\x3', '\x2', '\x2', '\x2', 'y', 'm', '\x3', '\x2', '\x2', '\x2', 
		'y', 'w', '\x3', '\x2', '\x2', '\x2', 'z', '\x17', '\x3', '\x2', '\x2', 
		'\x2', '{', '|', '\a', '\x1A', '\x2', '\x2', '|', '}', '\x5', '\x1E', 
		'\x10', '\x2', '}', '\x82', '\x5', '\x4', '\x3', '\x2', '~', '\x7F', '\a', 
		'\x1B', '\x2', '\x2', '\x7F', '\x83', '\x5', '\x18', '\r', '\x2', '\x80', 
		'\x81', '\a', '\x1B', '\x2', '\x2', '\x81', '\x83', '\x5', '\x4', '\x3', 
		'\x2', '\x82', '~', '\x3', '\x2', '\x2', '\x2', '\x82', '\x80', '\x3', 
		'\x2', '\x2', '\x2', '\x82', '\x83', '\x3', '\x2', '\x2', '\x2', '\x83', 
		'\x19', '\x3', '\x2', '\x2', '\x2', '\x84', '\x85', '\a', '\x1F', '\x2', 
		'\x2', '\x85', '\x86', '\x5', '\b', '\x5', '\x2', '\x86', '\x87', '\a', 
		' ', '\x2', '\x2', '\x87', '\x8A', '\x5', '\x1E', '\x10', '\x2', '\x88', 
		'\x89', '\a', '!', '\x2', '\x2', '\x89', '\x8B', '\a', '\'', '\x2', '\x2', 
		'\x8A', '\x88', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\x3', '\x2', 
		'\x2', '\x2', '\x8B', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8D', 
		'\x5', '\x1C', '\xF', '\x2', '\x8D', '\x1B', '\x3', '\x2', '\x2', '\x2', 
		'\x8E', '\x92', '\a', '\x1C', '\x2', '\x2', '\x8F', '\x93', '\x5', '\x6', 
		'\x4', '\x2', '\x90', '\x93', '\a', '\"', '\x2', '\x2', '\x91', '\x93', 
		'\a', '#', '\x2', '\x2', '\x92', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x92', 
		'\x90', '\x3', '\x2', '\x2', '\x2', '\x92', '\x91', '\x3', '\x2', '\x2', 
		'\x2', '\x93', '\x94', '\x3', '\x2', '\x2', '\x2', '\x94', '\x92', '\x3', 
		'\x2', '\x2', '\x2', '\x94', '\x95', '\x3', '\x2', '\x2', '\x2', '\x95', 
		'\x96', '\x3', '\x2', '\x2', '\x2', '\x96', '\x97', '\a', '\x1D', '\x2', 
		'\x2', '\x97', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x98', '\x99', '\b', 
		'\x10', '\x1', '\x2', '\x99', '\x9A', '\a', '\xF', '\x2', '\x2', '\x9A', 
		'\xAC', '\x5', '\x1E', '\x10', '\x13', '\x9B', '\x9C', '\a', '\a', '\x2', 
		'\x2', '\x9C', '\xAC', '\x5', '\x1E', '\x10', '\x12', '\x9D', '\xAC', 
		'\a', '\'', '\x2', '\x2', '\x9E', '\xAC', '\a', '(', '\x2', '\x2', '\x9F', 
		'\xAC', '\a', '*', '\x2', '\x2', '\xA0', '\xAC', '\a', ')', '\x2', '\x2', 
		'\xA1', '\xAC', '\a', '+', '\x2', '\x2', '\xA2', '\xAC', '\x5', '\x14', 
		'\v', '\x2', '\xA3', '\xA6', '\x5', ' ', '\x11', '\x2', '\xA4', '\xA6', 
		'\a', ',', '\x2', '\x2', '\xA5', '\xA3', '\x3', '\x2', '\x2', '\x2', '\xA5', 
		'\xA4', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xAC', '\x3', '\x2', '\x2', 
		'\x2', '\xA7', '\xA8', '\a', '\x15', '\x2', '\x2', '\xA8', '\xA9', '\x5', 
		'\x1E', '\x10', '\x2', '\xA9', '\xAA', '\a', '\x16', '\x2', '\x2', '\xAA', 
		'\xAC', '\x3', '\x2', '\x2', '\x2', '\xAB', '\x98', '\x3', '\x2', '\x2', 
		'\x2', '\xAB', '\x9B', '\x3', '\x2', '\x2', '\x2', '\xAB', '\x9D', '\x3', 
		'\x2', '\x2', '\x2', '\xAB', '\x9E', '\x3', '\x2', '\x2', '\x2', '\xAB', 
		'\x9F', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xA0', '\x3', '\x2', '\x2', 
		'\x2', '\xAB', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xA2', '\x3', 
		'\x2', '\x2', '\x2', '\xAB', '\xA5', '\x3', '\x2', '\x2', '\x2', '\xAB', 
		'\xA7', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xC7', '\x3', '\x2', '\x2', 
		'\x2', '\xAD', '\xAE', '\f', '\x11', '\x2', '\x2', '\xAE', '\xAF', '\t', 
		'\x2', '\x2', '\x2', '\xAF', '\xC6', '\x5', '\x1E', '\x10', '\x12', '\xB0', 
		'\xB1', '\f', '\x10', '\x2', '\x2', '\xB1', '\xB2', '\t', '\x3', '\x2', 
		'\x2', '\xB2', '\xC6', '\x5', '\x1E', '\x10', '\x11', '\xB3', '\xB4', 
		'\f', '\xF', '\x2', '\x2', '\xB4', '\xB5', '\t', '\x4', '\x2', '\x2', 
		'\xB5', '\xC6', '\x5', '\x1E', '\x10', '\x10', '\xB6', '\xB7', '\f', '\xE', 
		'\x2', '\x2', '\xB7', '\xB8', '\t', '\x5', '\x2', '\x2', '\xB8', '\xC6', 
		'\x5', '\x1E', '\x10', '\xF', '\xB9', '\xBA', '\f', '\r', '\x2', '\x2', 
		'\xBA', '\xBB', '\a', '\x6', '\x2', '\x2', '\xBB', '\xC6', '\x5', '\x1E', 
		'\x10', '\xE', '\xBC', '\xBD', '\f', '\f', '\x2', '\x2', '\xBD', '\xBE', 
		'\a', '\x5', '\x2', '\x2', '\xBE', '\xC6', '\x5', '\x1E', '\x10', '\r', 
		'\xBF', '\xC0', '\f', '\v', '\x2', '\x2', '\xC0', '\xC1', '\a', '\x3', 
		'\x2', '\x2', '\xC1', '\xC2', '\x5', '\x1E', '\x10', '\x2', '\xC2', '\xC3', 
		'\a', '\x4', '\x2', '\x2', '\xC3', '\xC4', '\x5', '\x1E', '\x10', '\f', 
		'\xC4', '\xC6', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xAD', '\x3', '\x2', 
		'\x2', '\x2', '\xC5', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xB3', 
		'\x3', '\x2', '\x2', '\x2', '\xC5', '\xB6', '\x3', '\x2', '\x2', '\x2', 
		'\xC5', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xBC', '\x3', '\x2', 
		'\x2', '\x2', '\xC5', '\xBF', '\x3', '\x2', '\x2', '\x2', '\xC6', '\xC9', 
		'\x3', '\x2', '\x2', '\x2', '\xC7', '\xC5', '\x3', '\x2', '\x2', '\x2', 
		'\xC7', '\xC8', '\x3', '\x2', '\x2', '\x2', '\xC8', '\x1F', '\x3', '\x2', 
		'\x2', '\x2', '\xC9', '\xC7', '\x3', '\x2', '\x2', '\x2', '\xCA', '\xCB', 
		'\a', ',', '\x2', '\x2', '\xCB', '\xCC', '\a', '\x17', '\x2', '\x2', '\xCC', 
		'\xCD', '\x5', '\x1E', '\x10', '\x2', '\xCD', '\xCE', '\a', '\x18', '\x2', 
		'\x2', '\xCE', '!', '\x3', '\x2', '\x2', '\x2', '\x17', '%', '+', '\x35', 
		'\x42', 'P', 'S', 'W', '\x63', 'j', 'm', 't', 'w', 'y', '\x82', '\x8A', 
		'\x92', '\x94', '\xA5', '\xAB', '\xC5', '\xC7',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
